### ISSUE TITLE
Why using default access modifier?

### ISSUE THREAD

**Issue by FranklinYinanDing** [linkedin/play-restli#13]
https://github.com/linkedin/play-restli/blob/9037a82a4203a6b59bb0ce65ffc447402e8c86cc/play-restli/src/main/java/com/linkedin/playrestli/DefaultHttpDispatcherProvider.java#L21

**Comment by FranklinYinanDing** [comment]
Same here https://github.com/linkedin/play-restli/blob/9037a82a4203a6b59bb0ce65ffc447402e8c86cc/play-restli/src/main/java/com/linkedin/playrestli/DefaultRestliConfigProvider.java#L15

**Comment by TylerHorth** [comment]
> Why using default access modifier?

Because I forgot :stuck_out_tongue_winking_eye: 

Fixing now
